language: c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

# Disable aimake for now, for performance purposes
script:
    - make
#   - mkdir build installdir
#   - cd build
#   - ../aimake -i ../installdir --without=gui

notifications:
    irc: "chat.freenode.net#FIQHack"
