language: c

os:
    - linux
    - osx

compiler:
    - clang

# Disable aimake for now, for performance purposes
script:
    - make install

notifications:
    irc: "chat.freenode.net#FIQHack"
    use_notice: true
    template:
      - "%{commit_subject} (%{result} %{branch} #%{build_number}) %{build_url}
        Diff: %{compare_url}"
