language: c

os:
    - linux
    - osx

compiler:
    - clang

# Disable aimake for now, for performance purposes
script:
    - make install

notifications:
    irc:
        channels: "chat.freenode.net#nethack4"
        on_success: always
        on_failure: always
        template:
          - "%{commit_subject} (%{result} %{branch} #%{build_number}) %{build_url}
            Diff: %{compare_url}"
