language: c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

script:
    - mkdir build installdir
    - cd build
    - ../aimake -i ../installdir --without=gui

notifications:
    - irc:
        channels:
            - "chat.freenode.net#fiqhack"
