CFLAGS=-g -O2 --std=c11 -DAIMAKE_NORETURN=_Noreturn
CXXFLAGS=-g -O2

CPPFLAGS+=-D"AIMAKE_ABI_VERSION(x)="
CPPFLAGS+=-D"AIMAKE_IMPORT(x)=x"
CPPFLAGS+=-D"AIMAKE_EXPORT(x)=x"
CPPFLAGS+=-DAIMAKE_BUILDOS_linux
CPPFLAGS+=-include _aimake_get_option.h

CPPFLAGS+=-Inethack/include
CPPFLAGS+=-Ilibnethack/include
CPPFLAGS+=-Ilibnethack_common/include
CPPFLAGS+=-Ilibuncursed/include
CPPFLAGS+=-Itilesets/include
CPPFLAGS+=-D_XOPEN_SOURCE=700
CPPFLAGS+=-D_REENTRANT
LDFLAGS+=-pthread

GAME_O_LIBNETHACK = allmain.o apply.o artifact.o attrib.o ball.o bones.o botl.o cmd.o    \
                    dbridge.o decl.o detect.o dig.o display.o dlb.o do.o do_name.o       \
                    do_wear.o dog.o dogmove.o dokick.o dothrow.o drawing.o dump.o        \
                    dungeon.o eat.o end.o engrave.o exper.o explode.o extralev.o files.o \
                    fountain.o hack.o history.o invent.o level.o light.o localtime.o     \
                    lock.o log.o makemon.o memfile.o messages.o mextra.o mhitm.o mhitq.o \
                    mhitu.o minion.o mklev.o mkmap.o mkmaze.o mkobj.o mkroom.o mon.o     \
                    mondata.o monmove.o monst.o mplayer.o mthrowu.o muse.o music.o       \
                    newrng.o o_init.o objects.o objnam.o options.o pager.o pickup.o      \
                    pline.o polyself.o potion.o pray.o priest.o prop.o quest.o           \
                    questpgr.o read.o readonly.o rect.o region.o restore.o role.o        \
                    rumors.o save.o shk.o shknam.o sit.o sounds.o sp_lev.o spell.o       \
                    steal.o steed.o symclass.o teleport.o timeout.o topten.o track.o     \
                    trap.o u_init.o uhitm.o vault.o version.o vision.o weapon.o were.o   \
                    wield.o windows.o wizard.o worm.o worn.o write.o zap.o

GAME_O_LIBNETHACK_COMMON = common_options.o hacklib.o menulist.o trietable.o utf8conv.o  \
                           xmalloc.o

GAME_O_NETHACK = brandings.o color.o dialog.o extrawin.o gameover.o getline.o keymap.o   \
                 main.o map.o menu.o messages.o motd.o options.o outchars.o              \
                 playerselect.o replay.o rungame.o sidebar.o status.o topten.o windows.o

GAME_O = $(GAME_O_LIBNETHACK:%.o=libnethack/src/%.o) \
         $(GAME_O_LIBNETHACK_COMMON:%.o=libnethack_common/src/%.o) \
         $(GAME_O_NETHACK:%.o=nethack/src/%.o) \
         libuncursed/src/libuncursed.o libuncursed/src/plugins.o \
         tilesets/src/tilesequence.o _aimake_get_option.o

MAKEDEFS_O = libnethack/util/makedefs.o libnethack/src/objects.o libnethack/src/monst.o

fiqhack: $(GAME_O) libuncursed/src/plugins/tty.c libuncursed/src/plugins/tty.cxx 
        $(CC) $(CPPFLAGS) $(LDFLAGS) $^ -ldl -lz -o $@ 

libnethack/util/makedefs: $(MAKEDEFS_O)
        $(CC) $(LDFLAGS) $^ -o $@

ALL_O = $(GAME_O) $(MAKEDEFS_O)

clean::
        rm -f fiqhack libnethack/util/makedefs
        rm -f $(ALL_O)

##### BASIC RULES AND AUTOMATIC DEPENDENCY GENERATION #####

MAKEFLAGS += --no-builtin-rules
.SUFFIXES:

%.o: %.c
        $(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -c -o $@ $<

%.d:
        $(CC) $(CFLAGS) $(CPPFLAGS) -MM -MP -MG -MT $*.o -MF $@ $*.c

ALL_D = $(ALL_O:%.o=%.d)
-include $(ALL_D)

distclean: clean
        rm -f $(ALL_D)

##### AUTOGENERATED SOURCE FILES #####

artinames.h: libnethack/include/artinames.h ;
libnethack/include/artinames.h: libnethack/include/artilist.h
        $(CPP) -DARTINAMES_H -o $@ $<

onames.h: libnethack/include/onames.h ;
libnethack/include/onames.h: libnethack/util/makedefs
        $< -o $@

pm.h: libnethack/include/pm.h ;
libnethack/include/pm.h: libnethack/util/makedefs
        $< -p $@

libnethack/src/readonly.c: libnethack/util/makedefs
        $< -m $@

date.h: libnethack/include/date.h ;
libnethack/include/date.h: libnethack/util/makedefs
        $< -v $@

verinfo.h: libnethack/include/verinfo.h ;
libnethack/include/verinfo.h: libnethack/util/makedefs
        $< -w $@

clean::
        rm -f libnethack/include/artinames.h libnethack/include/onames.h                 \
        libnethack/include/pm.h libnethack/src/readonly.c libnethack/include/date.h      \
        libnethack/include/verinfo.h
