#!/bin/bash
# Last modified by Alex Smith, 2014-10-21

set -e

test -f build-debian-package || echo Please run this script from its own directory.
test -f build-debian-package || exit 1

BUILDDIR=`mktemp -d /tmp/nh4build.XXXXXXXX`
SUBDIR='nethack4-4.3.0~beta2'
mkdir "$BUILDDIR/$SUBDIR"
cp -r ../* "$BUILDDIR/$SUBDIR"
cd "$BUILDDIR/$SUBDIR"
mv dist/debian debian
mv copyright debian/copyright
dpkg-buildpackage -us -uc
echo Output files written to "$BUILDDIR".
